In [9]:
# 파이선이 제공하는 우용한 자료구조들 중 리스트와 딕셔너리가 여러가지 응용분야에서 많이 활용되는 핵심요소임
# 하지만, 과학기술이나 금융분야에서는 더 빠른 연산이 가능한 특별한 자료 구조 필요
# 즉, 선형대수나 벡터공간이론 등 수학이론에 사용되는 배열(행/열로 구성) 자료가 필요 
# n차원의 배열을 쉬고 효율적으로 고성능으로 다루기 위한 목적으로 만들어 짐
# 특히, 디지털 이미지는 해당 영역에 대한 픽셀 정보를 2차원 배열로 인식해서 처리할 수 있음
# 데이터가 무엇이든 상관없이 그 데이터를 분석하려면 먼저 숫자배열로 변환하는 것이 우선되어야 함
# n차원 배열
# 파이썬의 리스트와는 달리 numpy 배열은 같은 종류의 데이터만 저장 가능
import numpy as np

# 파이썬 리스트
a = list([1,2,3,4,5])   # 숫자
b = list(['a','b','c','d','e'])  # 문자
c = list([0.1,'b', 'c', 1,2])  # 문자&숫자

print(type(a), type(b), type(c))

<class 'list'> <class 'list'> <class 'list'>


In [3]:
print(type(a), type(b), type(c))
print(type(a[0]),type(b[0]),type(c[0]))

<class 'list'> <class 'list'> <class 'list'>
<class 'int'> <class 'str'> <class 'float'>


In [13]:
# numpy 배열
# np.array(배열대상값들)
d = np.array([1,2,3,4,5])
e = np.array(['a','b','c','d','e'])  # 문자
f = np.array([0.1,'b', 'c', 1,2])  # 문자&숫자

print(type(d),type(e),type(f))

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [15]:
print(type(d[0]),type(e[0]),type(f[0]))

<class 'numpy.int32'> <class 'numpy.str_'> <class 'numpy.str_'>


In [18]:
print(d.shape)  # 배열의 요소 수
print(d.ndim)   # 배열의 차원수

(5,)
1


In [27]:
g = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(g.shape)
print(g.ndim)

(3, 3)
2


In [30]:
h = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(h.shape)
print(h.ndim)

(2, 2, 2)
3


In [32]:
# 배열 요소에 접근하기
print('배열 개별 요소:', d[0], d[2], d[4])
print('배열 부분요소1:', d[:3])   # 마지막 요소 제외
print('배열 부분요소2:', d[:3])
print('배열 전체요소:', d[:])

# 배열 세부 정보 확인
print('차원 정보', g.ndim)
print('요소 수', g.shape)
print('총 요소 수 ', g.size)
print('요소 자료형', g.dtype)
print('각 요소 자료크기', g.itemsize)
print('총 요소 자료크기', g.nbytes)

배열 개별 요소: 1 3 5
배열 부분요소1: [1 2 3]
배열 부분요소2: [1 2 3]
배열 전체요소: [1 2 3 4 5]
차원 정보 2
요소 수 (3, 3)
총 요소 수  9
요소 자료형 int32
각 요소 자료크기 4
총 요소 자료크기 36


In [42]:
# 난수를 이용한 numpy 배열 생성
# np.random.seed(181214)
print(np.random.randint(10))  # 0 ~ 4 사이 난수

3


In [45]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))   # 2차원
x3 = np.random.randint(10, size=(3,4,5))  # 3차원

print('x1',x1,'x2',x2,'x3',x3)

x1 [7 7 3 4 2 1] x2 [[2 3 5 9]
 [0 2 0 6]
 [4 1 4 9]] x3 [[[0 2 2 5 1]
  [9 4 5 5 9]
  [9 0 1 8 2]
  [4 6 9 0 6]]

 [[1 6 0 2 6]
  [8 0 8 2 2]
  [0 4 6 1 6]
  [5 0 0 3 3]]

 [[6 8 1 3 5]
  [8 3 3 2 9]
  [7 6 4 2 8]
  [3 1 6 0 5]]]


In [47]:
# 1-45 범위 난수 6개 생성(중복 불가)
x4 = np.random.randint(1,45,size=6)
print(x4)

[43  7 27 34 34 14]


In [91]:
# 1-45 범위 난수 6개 생성(중복 불가)
# np.unique() : 중복 제거 함수
x6 = np.random.choice(7, 6, replace=False)+1
print(x6)

[7 6 3 2 1 5]


In [50]:
# 1-45 범위 난수 6개 생성(중복 불가)
# np.unique() : 중복 제거 함수
x5 = np.unique(x4)
print(x5)

[ 7 14 27 34 43]


In [92]:
# 배열 슬라이싱 하기 : [시작: 끝: 스텝]
print('배열의 첫요소',e[0])
print('배열의 마지막요소1',e[-1])
print('배열의 마지막요소2',e[len(e)-1])

배열의 첫요소 a
배열의 마지막요소1 e
배열의 마지막요소2 e


In [95]:
i = np.arange(10)   # 0 - 9  정수 배열
print('처음부터 5번 요소까지', i[:5])
print('5번 요소부터', i[5:])
print('4번부터 8번 요소부터', i[4:9])
print('짝수 요소마다', i[:1:2])
print('2번 부터 짝수 요소 마다', i[2::2])
print('역순으로', i[::-1])
print('5번 요소부터 역순으로', i[5::-1])


처음부터 5번 요소까지 [0 1 2 3 4]
5번 요소부터 [5 6 7 8 9]
4번부터 8번 요소부터 [4 5 6 7 8]
짝수 요소마다 [0]
2번 부터 짝수 요소 마다 [2 4 6 8]
역순으로 [9 8 7 6 5 4 3 2 1 0]
5번 요소부터 역순으로 [5 4 3 2 1 0]


In [103]:
j = np.array([[12,5,2,4],[7,6,8,3],[1,6,7,9]])

print('3x4 배열', j)
print('2행 3열 배열', j[:2,:3])
print('3행 2열 배열', j[:3,:2])
print('행기준 역순 출력', j[::-1,:])
print('열기준 역순 출력', j[:,::-1])
print('역순 출력', j[::-1,::-1])
print('2열만 출력', j[:,1])
print('2행만 출력', j[1,:])

3x4 배열 [[12  5  2  4]
 [ 7  6  8  3]
 [ 1  6  7  9]]
2행 3열 배열 [[12  5  2]
 [ 7  6  8]]
3행 2열 배열 [[12  5]
 [ 7  6]
 [ 1  6]]
행기준 역순 출력 [[ 1  6  7  9]
 [ 7  6  8  3]
 [12  5  2  4]]
열기준 역순 출력 [[ 4  2  5 12]
 [ 3  8  6  7]
 [ 9  7  6  1]]
역순 출력 [[ 9  7  6  1]
 [ 3  8  6  7]
 [ 4  2  5 12]]
2열만 출력 [5 6 6]
2행만 출력 [7 6 8 3]
